source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "rails", "~> 7.1.0"
gem "mysql2", "~> 0.5"
gem "puma", "~> 6.0"

# Authentication
gem "devise", "~> 4.9"
gem "devise-jwt", "~> 0.11"

# Serializer
gem "active_model_serializers", "~> 0.10"

# CORS
gem "rack-cors"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
end

group :development do
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end
